
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://macariaband.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /

# Google tracking id

google-tracking-id: "G-R56ELBC637"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Davide Pastore"
title: "Macaria"
description: "Official website of the Folk/Death metal band from Italy. Includes a biography, releases, show dates, contact and a store."
keywords: "macaria, music, metal, strings, dramedy"
favicon: "/img/favicon.ico"

##########
# Navbar #
##########

navbar-offset-top: 180

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/macaria-logo.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The air is full of  bizzarre sound"
  - text: "Keep on dancing, keep on acting, keep on dancing"
  - text: "From on high I try to fight my fears<br/>
           contempling the living mosaic below me"
  - text: "We take our children and put them in this breeding<br/>
           where they shape them how society want"
  - text: "Legions of shaped minds march to the future<br/>
           breeded without way of choose"
  - text: "Eternal prize, lure for the lucky ones<br/>
           a comfortably illusion if your life has been damn"
  - text: "Why he still working?<br/>
           Love for he's family and he's dignity"
  - text: "Our leader, our float we will always trail<br/>
           our leader, our float has a bigger cock than your"
  - text: "Cage, cage in this opera<br/>
           We are all puppets, we are all puppets"
  - text: "We are all bounded to the strings of our wills<br/>
           We are all masters, everyone make the strings"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "macaria"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "macariametal@outlook.it"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/officialmacaria"
  - title: "twitter"
    url: "https://twitter.com/MacariaOfficial"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UC0SObLBSO9gix4QvG98OBTQ"
  - title: "instagram"
    url: "https://www.instagram.com/macaria_official"
  - title: "spotify"
    url: "https://open.spotify.com/artist/5hOkYzZorW88OYZETTQF6F"
  - title: "star"
    url: "https://www.reverbnation.com/macaria"
  - title: "github"
    url: "https://github.com/MacariaBand/macariaband.github.io"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/macaria-404.jpg"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the menu

pages_list:
  it:
    - title: 'Bio'
      external: False
      url: '#bio'
      name: 'bio'
    #- title: 'Blog'
    #  external: False
    #  url: '#latest-post'
    #  name: 'latest-post'
    #- title: 'Timeline'
    #  external: False
    #  url: '#timeline'
    #  name: 'timeline'
    - title: 'Release'
      external: False
      url: '#releases'
      name: 'releases'
    - title: 'Contatti'
      external: False
      url: '#contact'
      name: 'contact'
    - title: "A Strings' Dramedy"
      external: False
      url: 'a-strings-dramedy-it/'
      name: ''
    - title: 'Store'
      external: True
      url: 'https://macariaband.bandcamp.com/album/a-strings-dramedy'
      name: ''
    - title: 'Concerti'
      external: False
      url: 'concerti/'
      name: ''
  en:
    - title: 'Bio'
      external: False
      url: '#bio'
      name: 'bio'
    #- title: 'Blog'
    #  external: False
    #  url: '#latest-post'
    #  name: 'latest-post'
    #- title: 'Timeline'
    #  external: False
    #  url: '#timeline'
    #  name: 'timeline'
    - title: 'Releases'
      external: False
      url: '#releases'
      name: 'releases'
    - title: 'Contact'
      external: False
      url: '#contact'
      name: 'contact'
    - title: "A Strings' Dramedy"
      external: False
      url: 'a-strings-dramedy/'
      name: ''
    - title: 'Store'
      external: True
      url: 'https://macariaband.bandcamp.com/album/a-strings-dramedy'
      name: ''
    - title: 'Tour Dates'
      external: False
      url: 'tour-dates/'
      name: ''

#################
# EXTERNAL URLS #
#################

store_url: "https://macariaband.bandcamp.com/album/a-strings-dramedy"
iframe_url: "http://player.believe.fr/v2/3614970367581?embed=1&amp;embedType=53f5dde7044c7"

############
# FEED XML #
############
days_ago_published: 10

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-minifier
